using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

// Preview & apply tool to assign a placeholder sprite to any Image components with a null sprite
// Menu: Tools -> Preview Missing Sprite Fix
//       Tools -> Apply Missing Sprite Fix

public static class MissingSpriteFixer
{
    private const string PreviewPath = "Assets/Editor/MissingSpritesPreview.txt";
    private const string ApplyReportPath = "Assets/Editor/MissingSpritesApplyReport.txt";
    private const string PlaceholderPath = "Assets/Editor/placeholder.png";

    [MenuItem("Tools/Preview Missing Sprite Fix")]
    public static void Preview()
    {
        var entries = ScanForMissingSprites(out int prefabCount, out int sceneCount);
        var sb = new StringBuilder();
        sb.AppendLine("MissingSpritesPreview - generated by MissingSpriteFixer");
        sb.AppendLine();
        sb.AppendLine($"Prefabs scanned: {prefabCount}");
        sb.AppendLine($"Scenes scanned: {sceneCount}");
        sb.AppendLine($"Total Image components missing sprite: {entries.Count}");
        sb.AppendLine();
        foreach (var e in entries) sb.AppendLine(e);

        File.WriteAllText(PreviewPath, sb.ToString());
        AssetDatabase.ImportAsset(PreviewPath);

        EditorUtility.DisplayDialog("Preview Missing Sprite Fix", $"Scan complete. {entries.Count} missing sprites found. Preview saved to {PreviewPath}.", "OK");
        Debug.Log($"MissingSpriteFixer: preview complete. {entries.Count} missing sprites found. See {PreviewPath}");
    }

    [MenuItem("Tools/Apply Missing Sprite Fix")]
    public static void Apply()
    {
        if (!EditorUtility.DisplayDialog("Apply Missing Sprite Fix",
            "This will assign a placeholder sprite to every UnityEngine.UI.Image component that currently has no Sprite assigned across all prefabs and scenes. Backup your project or commit before proceeding. Continue?",
            "Yes", "No"))
        {
            return;
        }

        // Ensure placeholder exists (create if missing)
        EnsurePlaceholderExists();
        AssetDatabase.ImportAsset(PlaceholderPath);
        var placeholderSprite = AssetDatabase.LoadAssetAtPath<Sprite>(PlaceholderPath);
        if (placeholderSprite == null)
        {
            EditorUtility.DisplayDialog("Apply Missing Sprite Fix", "Could not load placeholder sprite at " + PlaceholderPath, "OK");
            return;
        }

        var entries = ScanForMissingSprites(out int prefabCount, out int sceneCount);
        int appliedCount = 0;
        var report = new StringBuilder();
        report.AppendLine("MissingSpritesApplyReport - generated by MissingSpriteFixer");
        report.AppendLine();
        report.AppendLine($"Prefabs scanned: {prefabCount}");
        report.AppendLine($"Scenes scanned: {sceneCount}");
        report.AppendLine();

        // Apply to prefabs
        string[] prefabGuids = AssetDatabase.FindAssets("t:Prefab");
        for (int i = 0; i < prefabGuids.Length; i++)
        {
            string prefabPath = AssetDatabase.GUIDToAssetPath(prefabGuids[i]);
            EditorUtility.DisplayProgressBar("Applying Placeholder", $"Processing prefab {i+1}/{prefabGuids.Length}: {prefabPath}", (float)i / prefabGuids.Length);

            var prefabRoot = PrefabUtility.LoadPrefabContents(prefabPath);
            bool changed = false;

            var images = prefabRoot.GetComponentsInChildren<Image>(true);
            foreach (var img in images)
            {
                if (img == null) continue;
                if (img.sprite == null)
                {
                    img.sprite = placeholderSprite;
                    changed = true;
                    appliedCount++;
                    report.AppendLine(prefabPath + " -> " + GetGameObjectPath(img.gameObject));
                }
            }

            if (changed)
            {
                PrefabUtility.SaveAsPrefabAsset(prefabRoot, prefabPath);
            }

            PrefabUtility.UnloadPrefabContents(prefabRoot);
        }

        // Apply to scenes
        string[] sceneGuids = AssetDatabase.FindAssets("t:Scene");
        string activeScenePath = SceneManager.GetActiveScene().path;
        for (int i = 0; i < sceneGuids.Length; i++)
        {
            string scenePath = AssetDatabase.GUIDToAssetPath(sceneGuids[i]);
            EditorUtility.DisplayProgressBar("Applying Placeholder", $"Processing scene {i+1}/{sceneGuids.Length}: {scenePath}", (float)i / sceneGuids.Length);

            var scene = EditorSceneManager.OpenScene(scenePath, OpenSceneMode.Single);
            if (!scene.isLoaded) continue;

            bool sceneChanged = false;
            var roots = scene.GetRootGameObjects();
            foreach (var root in roots)
            {
                var images = root.GetComponentsInChildren<Image>(true);
                foreach (var img in images)
                {
                    if (img == null) continue;
                    if (img.sprite == null)
                    {
                        img.sprite = placeholderSprite;
                        sceneChanged = true;
                        appliedCount++;
                        report.AppendLine(scenePath + " -> " + GetGameObjectPath(img.gameObject));
                    }
                }
            }

            if (sceneChanged)
            {
                EditorSceneManager.MarkSceneDirty(scene);
                EditorSceneManager.SaveScene(scene);
            }
        }

        // Restore active scene
        if (!string.IsNullOrEmpty(activeScenePath))
        {
            EditorSceneManager.OpenScene(activeScenePath, OpenSceneMode.Single);
        }

        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();
        EditorUtility.ClearProgressBar();

        report.Insert(2, $"Total placeholder sprites applied: {appliedCount}\n\n");
        File.WriteAllText(ApplyReportPath, report.ToString());
        AssetDatabase.ImportAsset(ApplyReportPath);

        EditorUtility.DisplayDialog("Apply Missing Sprite Fix", $"Applied placeholder to {appliedCount} Image components. Report saved to {ApplyReportPath}", "OK");
        Debug.Log($"MissingSpriteFixer: applied placeholder to {appliedCount} images. See {ApplyReportPath}");
    }

    private static List<string> ScanForMissingSprites(out int prefabCount, out int sceneCount)
    {
        var results = new List<string>();

        // Prefabs
        string[] prefabGuids = AssetDatabase.FindAssets("t:Prefab");
        prefabCount = prefabGuids.Length;
        for (int i = 0; i < prefabGuids.Length; i++)
        {
            string prefabPath = AssetDatabase.GUIDToAssetPath(prefabGuids[i]);
            var prefabRoot = PrefabUtility.LoadPrefabContents(prefabPath);

            var images = prefabRoot.GetComponentsInChildren<Image>(true);
            foreach (var img in images)
            {
                if (img == null) continue;
                if (img.sprite == null)
                {
                    results.Add(prefabPath + " -> " + GetGameObjectPath(img.gameObject));
                }
            }

            PrefabUtility.UnloadPrefabContents(prefabRoot);
        }

        // Scenes
        string[] sceneGuids = AssetDatabase.FindAssets("t:Scene");
        sceneCount = sceneGuids.Length;
        string activeScenePath = SceneManager.GetActiveScene().path;

        for (int i = 0; i < sceneGuids.Length; i++)
        {
            string scenePath = AssetDatabase.GUIDToAssetPath(sceneGuids[i]);
            var scene = EditorSceneManager.OpenScene(scenePath, OpenSceneMode.Single);
            if (!scene.isLoaded) continue;

            var roots = scene.GetRootGameObjects();
            foreach (var root in roots)
            {
                var images = root.GetComponentsInChildren<Image>(true);
                foreach (var img in images)
                {
                    if (img == null) continue;
                    if (img.sprite == null)
                    {
                        results.Add(scenePath + " -> " + GetGameObjectPath(img.gameObject));
                    }
                }
            }
        }

        // Restore active scene
        if (!string.IsNullOrEmpty(activeScenePath))
        {
            EditorSceneManager.OpenScene(activeScenePath, OpenSceneMode.Single);
        }

        return results;
    }

    private static string GetGameObjectPath(GameObject go)
    {
        if (go == null) return "<null>";
        var path = go.name;
        var t = go.transform.parent;
        while (t != null)
        {
            path = t.name + "/" + path;
            t = t.parent;
        }
        return path;
    }

    private static void EnsurePlaceholderExists()
    {
        if (File.Exists(PlaceholderPath)) return;

        // A 1x1 transparent PNG (base64)
        string base64 = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGNgYAAAAAMAAWgmWQ0AAAAASUVORK5CYII=";
        byte[] bytes = System.Convert.FromBase64String(base64);
        File.WriteAllBytes(PlaceholderPath, bytes);
    }
}
