using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

// Scans prefabs and scenes for Image components with missing sprites and for CinemachineLookActionBinder components.
// Writes a report to Assets/Editor/MissingAssetsReport.txt and logs summary to the Console.

public static class ReportMissingSpritesAndBinders
{
    [MenuItem("Tools/Report Missing Sprites & Cinemachine Binders")]
    public static void RunReport()
    {
        if (!EditorUtility.DisplayDialog("Report Missing Assets",
            "This will scan all prefabs and scenes for Image components that have no Sprite assigned and for CinemachineLookActionBinder components. A report will be written to Assets/Editor/MissingAssetsReport.txt. Continue?",
            "Yes", "No"))
        {
            return;
        }

        var report = new StringBuilder();
        var missingSpriteEntries = new List<string>();
        var binderEntries = new List<string>();

        // Prefabs
        string[] prefabGuids = AssetDatabase.FindAssets("t:Prefab");
        for (int i = 0; i < prefabGuids.Length; i++)
        {
            string prefabPath = AssetDatabase.GUIDToAssetPath(prefabGuids[i]);
            EditorUtility.DisplayProgressBar("Scanning Prefabs & Scenes", $"Scanning prefab {i+1}/{prefabGuids.Length}: {prefabPath}", (float)i / prefabGuids.Length);

            var prefabRoot = PrefabUtility.LoadPrefabContents(prefabPath);
            bool prefabHasIssue = false;

            // Images
            var images = prefabRoot.GetComponentsInChildren<Image>(true);
            foreach (var img in images)
            {
                if (img == null) continue;
                if (img.sprite == null)
                {
                    string path = prefabPath + " -> " + GetGameObjectPath(img.gameObject);
                    missingSpriteEntries.Add(path);
                    prefabHasIssue = true;
                }
            }

            // CinemachineLookActionBinder by type name to avoid assembly issues
            var components = prefabRoot.GetComponentsInChildren<MonoBehaviour>(true);
            foreach (var comp in components)
            {
                if (comp == null) continue;
                if (comp.GetType().Name == "CinemachineLookActionBinder")
                {
                    string path = prefabPath + " -> " + GetGameObjectPath(comp.gameObject);
                    binderEntries.Add(path);
                    prefabHasIssue = true;
                }
            }

            PrefabUtility.UnloadPrefabContents(prefabRoot);
        }

        // Scenes
        string[] sceneGuids = AssetDatabase.FindAssets("t:Scene");
        // Remember current active scene to restore later
        string activeScenePath = SceneManager.GetActiveScene().path;

        for (int i = 0; i < sceneGuids.Length; i++)
        {
            string scenePath = AssetDatabase.GUIDToAssetPath(sceneGuids[i]);
            EditorUtility.DisplayProgressBar("Scanning Prefabs & Scenes", $"Scanning scene {i+1}/{sceneGuids.Length}: {scenePath}", (float)i / sceneGuids.Length);

            var scene = EditorSceneManager.OpenScene(scenePath, OpenSceneMode.Single);
            if (!scene.isLoaded) continue;

            var roots = scene.GetRootGameObjects();
            foreach (var root in roots)
            {
                var images = root.GetComponentsInChildren<Image>(true);
                foreach (var img in images)
                {
                    if (img == null) continue;
                    if (img.sprite == null)
                    {
                        string path = scenePath + " -> " + GetGameObjectPath(img.gameObject);
                        missingSpriteEntries.Add(path);
                    }
                }

                var comps = root.GetComponentsInChildren<MonoBehaviour>(true);
                foreach (var comp in comps)
                {
                    if (comp == null) continue;
                    if (comp.GetType().Name == "CinemachineLookActionBinder")
                    {
                        string path = scenePath + " -> " + GetGameObjectPath(comp.gameObject);
                        binderEntries.Add(path);
                    }
                }
            }
        }

        // Restore previous active scene if possible
        if (!string.IsNullOrEmpty(activeScenePath))
        {
            EditorSceneManager.OpenScene(activeScenePath, OpenSceneMode.Single);
        }

        EditorUtility.ClearProgressBar();

        // Build report
        report.AppendLine("MissingSpritesReport - Generated by ReportMissingSpritesAndBinders");
        report.AppendLine();
        report.AppendLine($"Total prefabs scanned: {prefabGuids.Length}");
        report.AppendLine($"Total scenes scanned: {sceneGuids.Length}");
        report.AppendLine();

        report.AppendLine("Images with missing Sprite (img.sprite == null):");
        report.AppendLine("------------------------------------------------");
        if (missingSpriteEntries.Count == 0)
            report.AppendLine("(None found)");
        else
            foreach (var e in missingSpriteEntries) report.AppendLine(e);

        report.AppendLine();
        report.AppendLine("CinemachineLookActionBinder component locations:");
        report.AppendLine("------------------------------------------------");
        if (binderEntries.Count == 0)
            report.AppendLine("(None found)");
        else
            foreach (var e in binderEntries) report.AppendLine(e);

        // Save report
        string outPath = "Assets/Editor/MissingAssetsReport.txt";
        File.WriteAllText(outPath, report.ToString());
        AssetDatabase.ImportAsset(outPath);

        Debug.Log($"Report complete. Images missing sprites: {missingSpriteEntries.Count}. Cinemachine binders found: {binderEntries.Count}. Report written to {outPath}");
        EditorUtility.DisplayDialog("Report Missing Assets", $"Report complete. Images missing sprites: {missingSpriteEntries.Count}. Cinemachine binders found: {binderEntries.Count}. See {outPath}", "OK");
    }

    private static string GetGameObjectPath(GameObject go)
    {
        if (go == null) return "<null>";
        var path = go.name;
        var t = go.transform.parent;
        while (t != null)
        {
            path = t.name + "/" + path;
            t = t.parent;
        }
        return path;
    }
}
